// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp-U_hy1BI-bS-C_RkZASlBOVOwwFyb_o',
    appId: '1:486789140149:web:a518bd00bc95324b2938fc',
    messagingSenderId: '486789140149',
    projectId: 'attendease-aa7d7',
    authDomain: 'attendease-aa7d7.firebaseapp.com',
    storageBucket: 'attendease-aa7d7.firebasestorage.app',
    measurementId: 'G-KV5R631347',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRQJbAas4hveZ4OCOH9k8Oo4Q03q53XcI',
    appId: '1:486789140149:android:a1e48c53dadd9ee22938fc',
    messagingSenderId: '486789140149',
    projectId: 'attendease-aa7d7',
    storageBucket: 'attendease-aa7d7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp-U_hy1BI-bS-C_RkZASlBOVOwwFyb_o',
    appId: '1:486789140149:web:5a196e0ae0d753922938fc',
    messagingSenderId: '486789140149',
    projectId: 'attendease-aa7d7',
    authDomain: 'attendease-aa7d7.firebaseapp.com',
    storageBucket: 'attendease-aa7d7.firebasestorage.app',
    measurementId: 'G-3ZYLJ7HF0W',
  );
}
